### ISSUE TITLE
Feature request: Do not rerun the whole processing pipeline when adding filters in the web frontend

### ISSUE THREAD

**Issue by varisd** [hplt-project/OpusCleaner#104]
Currently, the whole filter pipeline is run when any of the filters is modified or a new filter is added to the end of the pipeline. After a certain point this slows down the process of filter adding/modifying significantly.

In practice, keeping a "checkpoint" of the sample dataset after applying all but last filter and modifying it by the final filter can speed up dataset and filter examination, making the process of seeing the effects of applying a specific filter at the end of a current pipeline less tedious.

I am not sure about the details of the current implementation. Are there any issues that could make implementation of this feature difficult?

**Comment by jelmervdl** [comment]
It already does this:

https://github.com/hplt-project/OpusCleaner/blob/afd9bc75b9abcfa8282fbda0785b44dfa01c9890/opuscleaner/server.py#L249-L263

This might be a frontend issue since it does fetch the entire sample after every change. Are you using the diff view? That thing is stupidly slow…
