### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by tomsbergmanis** [hplt-project/OpusCleaner#115]
Hi Jelmer and others,
After Nick's speech, I tried out OpusCleaner on Windows 11, but after successfully downloading corpora I was unable to filter it as the view which should have returned a sample of sentences was empty.
![image](https://github.com/hplt-project/OpusCleaner/assets/3306933/c88357ba-8db7-4b66-a232-a997edcfe673)

As I couldn't figure out what was wrong I added [error.log](https://github.com/hplt-project/OpusCleaner/files/12496380/error.log)

I would appreciate some help to get past this as the tool looks amazing and I would like to introduce it at our company!
Thanks in advance, 
Toms

**Comment by XapaJIaMnu** [comment]
User is running on windows and we fail to find gzip. How sad...

**Comment by tomsbergmanis** [comment]
I would be happy with any Windows-compatible solution as that would allow us to use it on our company's desktop machines, which, unfortunately, are Windows. I will try Windows Subsystem for Linux! 
Cheers!
