### ISSUE TITLE
Using OpusCleaner with local dataset

### ISSUE THREAD

**Issue by mzeidhassan** [hplt-project/OpusCleaner#138]
Hi team,
I am wondering if it is possible to use OpusCleaner with non-OPUS datasets. I want to use it on my own local datasets. Is this possible?
Thanks

**Comment by mzeidhassan** [comment]
Thanks @jelmervdl ! This is awesome. Closing the issue.

**Comment by XapaJIaMnu** [comment]
Let's add this to the readme before closing.

**Comment by jelmervdl** [comment]
Added to readme in 8d5c4a2.
