### ISSUE TITLE
opuscleaner-clean fails

### ISSUE THREAD

**Issue by bhaddow** [hplt-project/OpusCleaner#150]
Running `opuscleaner-clean` (using python 3.8.18) immediately fails

```
(opuscleaner) [lofn]bhaddow: opuscleaner-clean data/train-parts/HPLT-v1.1.bs-en.filters.json 
Traceback (most recent call last):
  File "/home/shared/bhaddow/anaconda3/envs/opuscleaner/bin/opuscleaner-clean", line 5, in <module>
    from opuscleaner.clean import main
  File "/mnt/startiger0/saga/raid0/bhaddow/code/OpusCleaner/opuscleaner/clean.py", line 25, in <module>
    from opuscleaner import logging
  File "/mnt/startiger0/saga/raid0/bhaddow/code/OpusCleaner/opuscleaner/logging.py", line 115, in <module>
    class Logger:
  File "/mnt/startiger0/saga/raid0/bhaddow/code/OpusCleaner/opuscleaner/logging.py", line 119, in Logger
    stack: deque[UUID]
TypeError: 'type' object is not subscriptable
(opuscleaner) [lofn]bhaddow: python --version
Python 3.8.18
```

I cannot install the dependencies in Python 3.10

**Comment by PinzhenChen** [comment]
I have python 3.9 and I was able to run opus cleaner-clean end-to-end.

It might be some rules you are using or just generally a problem with the python version? https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature

**Comment by jelmervdl** [comment]
This is a general python problem. `deque` only became subscriptable in 3.9. Really, CI should probably be set to use 3,8 so these errors pop up more quickly. I used 3.9 when developing, but tried (not hard enough) to stay compatible with 3.8. You can replace with `Deque[UUID]` imported from `typing`.

**Comment by bhaddow** [comment]
If I fix `logging.py` then it fails elsewhere:

```
(opuscleaner) [lofn]bhaddow: opuscleaner-clean data/train-parts/HPLT-v1.1.bs-en.filters.json 
Traceback (most recent call last):
  File "/home/shared/bhaddow/anaconda3/envs/opuscleaner/bin/opuscleaner-clean", line 5, in <module>
    from opuscleaner.clean import main
  File "/home/shared/bhaddow/anaconda3/envs/opuscleaner/lib/python3.8/site-packages/opuscleaner/clean.py", line 32, in <module>
    PrintQueue = SimpleQueue[Union[None,bytes]]
TypeError: 'type' object is not subscriptable
```

I can't immediately see how to fix this, so I will try upgrading to 3.9

**Comment by jelmervdl** [comment]
Ayy, yes. Two options that might work:
1. Adding `from __future__ import annotations` to `clean.py`. 
2. Turn it into a string, which should be okay with most type checkers. E.g. `PrintQueue = "SimpleQueue[Union[None,bytes]]"`
3. Just say Python 3.9 is the lowest version supported and never run into this again 🤷

**Comment by bhaddow** [comment]
I've upgraded to Python 3.9 (so implicitly choosing option 3)

**Comment by jelmervdl** [comment]
Should be fixed by https://github.com/hplt-project/OpusCleaner/commit/4e8c7b46244da1d2382f8f2cef36cd7ec11f40e4
