### ISSUE TITLE
Do not assume stderr output is always an error

### ISSUE THREAD

**Issue by XapaJIaMnu** [hplt-project/OpusCleaner#68]
Some tools write debug output on stderr and this can't always be disabled, unfortunately.

Instead, we should monitor return code. Assume non-zero return codes are an error and only then display stderr/failure mark on the GUI. Opinions?

**Comment by ZJaume** [comment]
I'm in favor of just checking the exit code, all of bitextor/* tools use stderr to print logging messages.

**Comment by jelmervdl** [comment]
The code checks for return code to figure out if something was wrong, but doesn't communicate that code to the frontend I believe. That return code should be the only thing that influences the "failure" state. That can be fixed.

My previous UI had a way to toggle seeing the stderr output of each step. I'll need to bring that back. Having access to the logging messages seems like a very useful thing to have when you're developing a filter pipeline for a dataset.

Todo: 
- [ ] Use process return code to determine whether step failed or not
- [ ] Make stderr toggleable for each filter step
- [ ] Don't show stderr for filter step by default unless its return code indicated a failure.
