### ISSUE TITLE
OpusCleaner leaves `\r` in output?

### ISSUE THREAD

**Issue by jelmervdl** [hplt-project/OpusCleaner#81]
Nick ran into some issues with spurious `\r` carriage return characters in the output files. That should not happen.

**Comment by ZJaume** [comment]
Bifixer should be able to fix that type of things

**Comment by XapaJIaMnu** [comment]
I don't run everything through bifixer as allegedly some of the corpora are clean. Allegedly.

**Comment by ZJaume** [comment]
Bifixer can be run on everything as it doesn't discard sentences and can fix many small things.

**Comment by jelmervdl** [comment]
In this case I'd say it is a bug in OpusCleaner because I've written code that reads like `for line in sys.stdin: do_something(line.rstrip('\n'))` to be a bit cautious to not strip any empty `\t` from the end of a line. But this also leaves the `\r` on some datasets that use Windows line endings. There's also code in there that just assumes `line[:-1]` will strip all the newline characters.
