### ISSUE TITLE
Boolean filter properties are always `true`

### ISSUE THREAD

**Issue by jelmervdl** [hplt-project/OpusCleaner#83]
Frontend code seems to encode them in JSON as `"true"` and `"false"` strings. Backend interpret both of these as true?

Edit: even when unchecked the DEBUG boolean parameter I added was always submitted as `"true"` to the backend when requesting a sample. Something is broken there.

**Comment by XapaJIaMnu** [comment]
So this would affect filters such as bifixer/bicleaner/ anything that has a tickbox would always be true in the backend?

**Comment by jelmervdl** [comment]
I’m not entirely sure when this bug occurs. It seems to be a state issue in the frontend, and I’m wondering why I never noticed it before.

You’d think I would have noticed it if toggling a toggle wouldn’t have any effect…
