### ISSUE TITLE
Downloads keep running after interrupt

### ISSUE THREAD

**Issue by jindrahelcl** [hplt-project/OpusCleaner#88]
After Ctrl-C-ing a server which is currently downloading stuff, the downloads keep running in the background.

**Comment by jindrahelcl** [comment]
.. also maybe not just dowload processes; if I try to re-run the server on the same port it complains that the port is in use. So you need to kill the process manually first.

**Comment by jelmervdl** [comment]
Should be fixed by 67e046e9795ef81f472faa3cce5f5a8b2089ff5c.
